language: java
addons:
  sonarcloud:
    organization: "davidgfolch-github"
    token:
      secure: "HlII5SPMD+zL8jGIOE+TGu7YCSbW/15NhnWX3fO/tZ0EcjwwfyEAYhw8HNqGcP/3VwbBMlRkUQgOWXoX7QJH1bZCplCnA7PAWcM0uSkxjFsHC+FibrCMSH30ciSLIUQerg1pTxzYNnf3/kE7H68VPFEvRXPnfMJUgiwECFYepRTZc4gs8B7ISzt6/i5F0OVt7C0Po8uE+zPV12gf6iASoLNDMWbVBE/fg/YyBmMKy8Q/AJX48Hah8UQRZB/1lzLIwHi+7Q2z7wtCAZv0Vj8jE7IpyvzPjNbFg5kozGE+NX2jYtWu02g/gHQNvYR6pjjPjM5yt8jn3dq1iKguWZ49wzFP8PdCTn3/ygIKoBW1XKRxrtT0QWInptXKG5Uq1MbnB4ZCfq6/o30uUkx6adHk+mdzLxo7AgzUWq6203SMLjz5ZmjZcSZPmKkfi7WDwhJXeafSiRnSvW2S55CZ2qdoaM2H6hY2nBty9zmSpUQiavHvN0AXhAFdOPzUF/Uc+5owQz3l5dUpTSpSZ8z+fgkiucHazMucL9PxzH7aZ6HgO6rdJ6s8xdk6lPMFdQwNUnrZBMwl7nkPgkCBxRGJ+BNYcPX5g+PFsJRNFq6fZbYImwL8T136Gfst20+StZyHvZ2cMdbm26m/m6TNvlQhvH48KSPlCh5X3GwIOQRlFdBBkuw="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
